server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
pojoListener:
  enabled: false
messageListener:
  implementation: batchListener
livefeed:
  processor:
    minSleep: 500
    maxSleep: 5000
    errorTimeOut: 50