server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
pojoListener:
  enabled: false
messageListener:
  implementation: batchListener
livefeed:
  processor:
    minSleep: 100
    maxSleep: 500
    errorTimeOut: 1000